# Generated by Django 4.2.1 on 2023-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional_nombre', models.CharField(max_length=255)),
                ('profesional_barberia', models.CharField(max_length=255)),
                ('profesional_horarios', models.CharField(max_length=255)),
            ],
        ),
    ]
