# Generated by Django 4.2.1 on 2023-06-20 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0003_remove_barberia_propietario'),
        ('profesional', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='barberia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberia.barberia', verbose_name='Barbería'),
        ),
    ]
