# Generated by Django 4.2.1 on 2023-06-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0003_alter_profesional_barberia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterModelManagers(
            name='profesional',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='active',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='user',
        ),
        migrations.AlterField(
            model_name='profesional',
            name='nombre',
            field=models.CharField(blank=True, default='barbero', max_length=50, null=True),
        ),
    ]
