# Generated by Django 4.2.1 on 2023-06-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='contraseña',
        ),
    ]
