# Generated by Django 4.2.1 on 2023-06-21 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0004_alter_propietario_options_alter_propietario_managers_and_more'),
        ('post', '0003_post_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('propietario',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='barberia',
        ),
        migrations.RemoveField(
            model_name='post',
            name='usuario',
        ),
        migrations.AddField(
            model_name='post',
            name='propietario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='propietario.propietario', verbose_name='Propietario'),
        ),
    ]
