# Generated by Django 4.2.1 on 2023-06-10 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barberia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberia.barberia', verbose_name='Barberia')),
            ],
            options={
                'ordering': ('dni',),
            },
            managers=[
                ('objects_all', django.db.models.manager.Manager()),
            ],
        ),
    ]
