# Generated by Django 4.2.1 on 2023-06-20 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barberia', '0002_barberia_propietario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barberia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='barberia', to='barberia.barberia', verbose_name='barberia')),
                ('propietario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('propietario',),
            },
        ),
    ]
