# Generated by Django 4.2.1 on 2023-06-20 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propietario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propietario',
            options={'ordering': ('dni',)},
        ),
        migrations.AlterModelManagers(
            name='propietario',
            managers=[
                ('objects_all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='propietario',
        ),
        migrations.AddField(
            model_name='propietario',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='propietario',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='propietario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
