# Generated by Django 4.2.1 on 2023-06-20 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0003_remove_barberia_propietario'),
        ('propietario', '0002_alter_propietario_options_alter_propietario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='barberia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barberia', to='barberia.barberia', verbose_name='barberia'),
        ),
    ]
