# Generated by Django 4.2.1 on 2023-06-20 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propietario', '0003_alter_propietario_barberia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propietario',
            options={'ordering': ('propietario',)},
        ),
        migrations.AlterModelManagers(
            name='propietario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='active',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='user',
        ),
        migrations.AddField(
            model_name='propietario',
            name='propietario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barberia', to=settings.AUTH_USER_MODEL, verbose_name='barberia'),
        ),
    ]
