# Generated by Django 4.2.1 on 2023-06-22 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propietario', '0004_alter_propietario_options_alter_propietario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='propietario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barberia', to=settings.AUTH_USER_MODEL, verbose_name='propietario'),
        ),
    ]
