# Generated by Django 4.2.1 on 2023-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_telefono', models.IntegerField()),
            ],
            options={
                'ordering': ('cliente_nombre',),
            },
        ),
    ]
