# Generated by Django 4.2.1 on 2023-06-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barberia_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('barberia_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('barberia_horario', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
