# Generated by Django 4.2.1 on 2023-06-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barberia',
            options={'ordering': ('barberia_nombre',)},
        ),
    ]
