# Generated by Django 4.2.1 on 2023-06-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberia', '0002_alter_barberia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberia',
            name='barberia_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
