# Generated by Django 4.2.1 on 2023-06-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barberia', '0001_initial'),
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberia.barberia', verbose_name='Barberia')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional', verbose_name='Profesional')),
            ],
            options={
                'ordering': ['-dia'],
            },
        ),
    ]
