# Generated by Django 4.2.1 on 2023-06-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0001_initial'),
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional', verbose_name='Profesional'),
        ),
    ]
