# Generated by Django 4.2.1 on 2023-06-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0004_alter_profesional_options_alter_profesional_managers_and_more'),
        ('turno', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profesional.profesional', verbose_name='Profesional'),
        ),
    ]
