# Generated by Django 4.2.1 on 2023-06-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0003_alter_turno_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
