# Generated by Django 4.2.1 on 2023-06-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0004_turno_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='comentario',
        ),
    ]
